name: memo_neet
description: A new Flutter project.
version: 2.2.4+5
environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  flutter_svg: ^1.1.6
  shared_preferences: ^2.1.0
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_database: ^10.0.9
  firebase_storage:
  firebase_crashlytics: ^3.3.5

  # state management
  provider: ^6.0.5

  # databas
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.2
  path_provider: ^2.0.14
  google_sign_in: ^6.1.0
  country_pickers: ^2.0.0
  cached_network_image: ^3.2.3
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.6
  the_apple_sign_in: ^1.1.1
  carrier_info: ^2.0.8
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  simple_progress_indicators: ^0.2.0
  percent_indicator: ^4.2.3
  flutter_native_splash: ^2.2.19
  pin_code_fields: ^7.4.0
  uiblock: ^2.0.2
  another_stepper: ^1.2.2
  drop_shadow: ^0.1.0
  youtube_player_flutter: ^8.1.2
  flutter_spinkit: ^5.2.0
  photo_view: ^0.14.0
  in_app_purchase: ^3.1.7
  google_mobile_ads: ^3.0.0
  flip_card: ^0.7.0
  fluttertoast: ^8.2.2
  youtube_player_iframe: ^4.0.4
  pod_player: ^0.2.1
  youtube_explode_dart: ^2.0.1
  facebook_audience_network: ^1.0.1
  sqlite3: ^2.1.0
  webview_flutter: ^4.2.2
  just_audio: ^0.9.34
  visibility_detector: ^0.3.3
  screen_protector: ^1.3.0
  otpless_flutter: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/memoneet_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter_native_splash:
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/doctor.svg
    - jsonFiles/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
