// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGKfhRNIfvf-DQqOEo-thAzEkGZW6vzNY',
    appId: '1:540788350539:web:d79a54859c3bd1318937ce',
    messagingSenderId: '540788350539',
    projectId: 'memoneet-5498',
    authDomain: 'memoneet-5498.firebaseapp.com',
    databaseURL: 'https://memoneet-5498.firebaseio.com',
    storageBucket: 'memoneet-5498.appspot.com',
    measurementId: 'G-48KVRB0F19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAwwzUhSO89-dRvGJHZIINU0i9mCR5zZc',
    appId: '1:540788350539:android:85b4e121275ae7968937ce',
    messagingSenderId: '540788350539',
    projectId: 'memoneet-5498',
    databaseURL: 'https://memoneet-5498.firebaseio.com',
    storageBucket: 'memoneet-5498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFveqJYsnTSmlhWhDLTRB4WhIDAOpSgLU',
    appId: '1:540788350539:ios:53d0e9cc0afde2c88937ce',
    messagingSenderId: '540788350539',
    projectId: 'memoneet-5498',
    databaseURL: 'https://memoneet-5498.firebaseio.com',
    storageBucket: 'memoneet-5498.appspot.com',
    androidClientId: '540788350539-01sdjtmprdb11qvhaa18627vqdke6g5p.apps.googleusercontent.com',
    iosBundleId: 'com.memoapp.memoneet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFveqJYsnTSmlhWhDLTRB4WhIDAOpSgLU',
    appId: '1:540788350539:ios:53d0e9cc0afde2c88937ce',
    messagingSenderId: '540788350539',
    projectId: 'memoneet-5498',
    databaseURL: 'https://memoneet-5498.firebaseio.com',
    storageBucket: 'memoneet-5498.appspot.com',
    androidClientId: '540788350539-01sdjtmprdb11qvhaa18627vqdke6g5p.apps.googleusercontent.com',
    iosBundleId: 'com.memoapp.memoneet',
  );
}
